package View;


import javax.swing.JOptionPane;
import Controle.ConexaoBD;
import Controle.DaoLogin;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adn_e
 */
public class LoginView extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        UserTField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        PasswordTField = new javax.swing.JPasswordField();
        LoginAreaPane = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LoginImgLabel = new javax.swing.JLabel();
        frameDragLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(613, 510));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(51, 51, 51));
        backgroundPanel.setEnabled(false);
        backgroundPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundPanelMouseDragged(evt);
            }
        });
        backgroundPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundPanelMousePressed(evt);
            }
        });
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(231, 233, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userLabel.setText("Usuário:");
        jPanel2.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));
        jPanel2.add(UserTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, -1));

        passLabel.setText("Senha:");
        jPanel2.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        PasswordTField.setToolTipText("");
        PasswordTField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordTFieldFocusGained(evt);
            }
        });
        PasswordTField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordTFieldKeyPressed(evt);
            }
        });
        jPanel2.add(PasswordTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, -1));

        LoginAreaPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbuttonblue96x25.png"))); // NOI18N
        btnLogin.setToolTipText("Pressione para Logar");
        btnLogin.setContentAreaFilled(false);
        btnLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbuttongreen96x25.png"))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        btnLeave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelbuttonblue96x25.png"))); // NOI18N
        btnLeave.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelbuttonblackwhite96x25.png"))); // NOI18N
        btnLeave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLeaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginAreaPaneLayout = new javax.swing.GroupLayout(LoginAreaPane);
        LoginAreaPane.setLayout(LoginAreaPaneLayout);
        LoginAreaPaneLayout.setHorizontalGroup(
            LoginAreaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginAreaPaneLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(LoginAreaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        LoginAreaPaneLayout.setVerticalGroup(
            LoginAreaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginAreaPaneLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel2.add(LoginAreaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, 230));

        backgroundPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 235, 350));

        jPanel1.setBackground(new java.awt.Color(231, 233, 236));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginBannerBlack.png"))); // NOI18N
        jPanel1.add(LoginImgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        backgroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 350));

        frameDragLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragLabelMouseDragged(evt);
            }
        });
        frameDragLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragLabelMousePressed(evt);
            }
        });
        backgroundPanel.add(frameDragLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 612, 30));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 613, 510));
        backgroundPanel.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(613, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeaveMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnLeaveMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        DaoLogin loginDao = new DaoLogin();

        if (loginDao.checkLogin(UserTField.getText(), PasswordTField.getText()) == true) {
            MainView tela = new MainView();
            tela.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Senha incorreta!!");
        }

    }//GEN-LAST:event_btnLoginMouseClicked

    private void PasswordTFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordTFieldFocusGained

    }//GEN-LAST:event_PasswordTFieldFocusGained

    private void PasswordTFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DaoLogin loginDao = new DaoLogin();

            if (loginDao.checkLogin(UserTField.getText(), PasswordTField.getText()) == true) {
                MainView tela = new MainView();
                tela.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Senha incorreta!!");
            }
        }
    }//GEN-LAST:event_PasswordTFieldKeyPressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:


    }//GEN-LAST:event_formMouseDragged

    private void frameDragLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragLabelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);


    }//GEN-LAST:event_frameDragLabelMouseDragged

    private void frameDragLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragLabelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragLabelMousePressed

    private void backgroundPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_backgroundPanelMouseDragged

    private void backgroundPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_backgroundPanelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginAreaPane;
    private javax.swing.JLabel LoginImgLabel;
    private javax.swing.JPasswordField PasswordTField;
    private javax.swing.JTextField UserTField;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel frameDragLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
