package View;


import java.awt.Point;
import javax.swing.JOptionPane;

public class MainView extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    public MainView() {
        initComponents();
    }

    private static Point point = new Point();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        MainAreaPane = new javax.swing.JPanel();
        btnClientArea = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnProductsArea = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSells = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HeaderLabel = new javax.swing.JLabel();
        btnLogOff = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        backgroundPanel.setBackground(new java.awt.Color(51, 51, 51));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(600, 500));
        backgroundPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundPanelMouseDragged(evt);
            }
        });
        backgroundPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundPanelMousePressed(evt);
            }
        });
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainAreaPane.setBackground(new java.awt.Color(250, 250, 250));
        MainAreaPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 2, true));
        MainAreaPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientArea.setBackground(new java.awt.Color(102, 102, 102));
        btnClientArea.setForeground(new java.awt.Color(102, 102, 102));
        btnClientArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user100x100.png"))); // NOI18N
        btnClientArea.setBorder(null);
        btnClientArea.setBorderPainted(false);
        btnClientArea.setContentAreaFilled(false);
        btnClientArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientArea.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user100x100green.png"))); // NOI18N
        btnClientArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientAreaMouseClicked(evt);
            }
        });
        MainAreaPane.add(btnClientArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 119, 100, 100));

        jLabel1.setForeground(new java.awt.Color(45, 45, 81));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(btnClientArea);
        jLabel1.setText("Area de Clientes");
        MainAreaPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 230, 100, -1));

        btnProductsArea.setBackground(new java.awt.Color(102, 102, 102));
        btnProductsArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EletronicsIcon100x100.png"))); // NOI18N
        btnProductsArea.setContentAreaFilled(false);
        btnProductsArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProductsArea.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EletronicsIcon100x100green.png"))); // NOI18N
        btnProductsArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductsAreaMouseClicked(evt);
            }
        });
        MainAreaPane.add(btnProductsArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 124, 100));

        jLabel2.setForeground(new java.awt.Color(45, 45, 81));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setLabelFor(btnProductsArea);
        jLabel2.setText("Area de Produtos");
        MainAreaPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 124, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SearchIcon100x100.png"))); // NOI18N
        btnSearch.setContentAreaFilled(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SearchIcon100x100green.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        MainAreaPane.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 260, 100, 100));
        btnSearch.getAccessibleContext().setAccessibleName("btnSearch");
        btnSearch.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setForeground(new java.awt.Color(45, 45, 81));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pesquisar");
        MainAreaPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 360, 100, -1));

        btnSells.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SellsIcon100x100.png"))); // NOI18N
        btnSells.setContentAreaFilled(false);
        btnSells.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSells.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SellsIcon100x100green.png"))); // NOI18N
        btnSells.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSellsMouseClicked(evt);
            }
        });
        MainAreaPane.add(btnSells, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 100, 100));

        jLabel4.setForeground(new java.awt.Color(45, 45, 81));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setLabelFor(btnSells);
        jLabel4.setText("Area de Vendas");
        MainAreaPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 100, -1));

        HeaderLabel.setBackground(new java.awt.Color(250, 250, 250));
        HeaderLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Header450x.png"))); // NOI18N
        HeaderLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 2, true));
        MainAreaPane.add(HeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 100));
        HeaderLabel.getAccessibleContext().setAccessibleName("Header");

        btnLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-offblue25x25.png"))); // NOI18N
        btnLogOff.setToolTipText("Logout");
        btnLogOff.setContentAreaFilled(false);
        btnLogOff.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-offgreen25x25.png"))); // NOI18N
        btnLogOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOffMouseClicked(evt);
            }
        });
        MainAreaPane.add(btnLogOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 25, 25));

        backgroundPanel.add(MainAreaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 40, 450, 430));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closebuttonred25x25.png"))); // NOI18N
        jButton1.setToolTipText("Close App");
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closebuttonred2-25x25.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        backgroundPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 25, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnProductsAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsAreaMouseClicked
        // TODO add your handling code here:
        ProductsAreaView productsView = new ProductsAreaView();
        productsView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductsAreaMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseDragged

    private void btnClientAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientAreaMouseClicked
        // TODO add your handling code here:
        ClientsAreaView clientTable = new ClientsAreaView();
        this.dispose();
        clientTable.setVisible(true);

    }//GEN-LAST:event_btnClientAreaMouseClicked

    private void btnLogOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOffMouseClicked
        LoginView loginView = new LoginView();

        this.dispose();
        loginView.setVisible(true);
    }//GEN-LAST:event_btnLogOffMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        SearchView searchTable = new SearchView();
        searchTable.setVisible(true);
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSellsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellsMouseClicked
        NewSaleView salesTable = new NewSaleView();
        salesTable.setVisible(true);
    }//GEN-LAST:event_btnSellsMouseClicked

    private void backgroundPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_backgroundPanelMouseDragged

    private void backgroundPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_backgroundPanelMousePressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JPanel MainAreaPane;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnClientArea;
    private javax.swing.JButton btnLogOff;
    private javax.swing.JButton btnProductsArea;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSells;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
