package View;


import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;

/**
 *
 * @author adaulan.eogomes
 */
public class ProductsAreaView extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    public ProductsAreaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        ProductsAreaPane = new javax.swing.JPanel();
        btnCadProduct = new javax.swing.JButton();
        cadProductLabel = new javax.swing.JLabel();
        btnReturnMain = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnUpdateProduct = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRemoveProduct = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HeaderLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundPanel.setBackground(new java.awt.Color(51, 51, 51));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(600, 500));
        backgroundPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundPanelMouseDragged(evt);
            }
        });
        backgroundPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundPanelMousePressed(evt);
            }
        });
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductsAreaPane.setBackground(new java.awt.Color(250, 250, 250));
        ProductsAreaPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 2, true));
        ProductsAreaPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadProduct.setBackground(new java.awt.Color(102, 102, 102));
        btnCadProduct.setForeground(new java.awt.Color(102, 102, 102));
        btnCadProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product100x100.png"))); // NOI18N
        btnCadProduct.setBorder(null);
        btnCadProduct.setBorderPainted(false);
        btnCadProduct.setContentAreaFilled(false);
        btnCadProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadProduct.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product100x100green.png"))); // NOI18N
        btnCadProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadProductMouseClicked(evt);
            }
        });
        ProductsAreaPane.add(btnCadProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 119, 100, 100));

        cadProductLabel.setForeground(new java.awt.Color(45, 45, 81));
        cadProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadProductLabel.setLabelFor(btnCadProduct);
        cadProductLabel.setText("Cadastrar Produto");
        ProductsAreaPane.add(cadProductLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 230, 150, -1));

        btnReturnMain.setBackground(new java.awt.Color(102, 102, 102));
        btnReturnMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return100x100.png"))); // NOI18N
        btnReturnMain.setContentAreaFilled(false);
        btnReturnMain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReturnMain.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return100x100green.png"))); // NOI18N
        btnReturnMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMainMouseClicked(evt);
            }
        });
        ProductsAreaPane.add(btnReturnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 100, 100));

        jLabel2.setForeground(new java.awt.Color(45, 45, 81));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setLabelFor(btnReturnMain);
        jLabel2.setText("Retornar");
        ProductsAreaPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 124, -1));

        btnUpdateProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/changeproduct100x100.png"))); // NOI18N
        btnUpdateProduct.setContentAreaFilled(false);
        btnUpdateProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateProduct.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/changeproduct100x100green.png"))); // NOI18N
        btnUpdateProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateProductMouseClicked(evt);
            }
        });
        ProductsAreaPane.add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 260, 100, 100));
        btnUpdateProduct.getAccessibleContext().setAccessibleName("btnSearch");
        btnUpdateProduct.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setForeground(new java.awt.Color(45, 45, 81));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Alterar Produtos");
        ProductsAreaPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 130, 20));

        btnRemoveProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2removeproduct100x100.png"))); // NOI18N
        btnRemoveProduct.setContentAreaFilled(false);
        btnRemoveProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemoveProduct.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/removeproduct100x100.png"))); // NOI18N
        btnRemoveProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveProductMouseClicked(evt);
            }
        });
        ProductsAreaPane.add(btnRemoveProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 100, 100));

        jLabel4.setForeground(new java.awt.Color(45, 45, 81));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setLabelFor(btnRemoveProduct);
        jLabel4.setText("Remover Produtos");
        ProductsAreaPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 230, 130, -1));

        HeaderLabel.setBackground(new java.awt.Color(250, 250, 250));
        HeaderLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Header450x.png"))); // NOI18N
        HeaderLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 2, true));
        ProductsAreaPane.add(HeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 100));
        HeaderLabel.getAccessibleContext().setAccessibleName("Header");

        backgroundPanel.add(ProductsAreaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 40, 450, 430));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closebuttonred25x25.png"))); // NOI18N
        jButton1.setToolTipText("Close App");
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closebuttonred2-25x25.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        backgroundPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 25, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReturnMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMainMouseClicked
        MainView mainView = new MainView();
        this.dispose();
        mainView.setVisible(true);
    }//GEN-LAST:event_btnReturnMainMouseClicked

    private void btnCadProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadProductMouseClicked

        new CadProductView().setVisible(true);
    }//GEN-LAST:event_btnCadProductMouseClicked

    private void backgroundPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_backgroundPanelMouseDragged

    private void backgroundPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_backgroundPanelMousePressed

    private void btnRemoveProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveProductMouseClicked
        RemoveProductView remove = new RemoveProductView();
        remove.setVisible(true);
    }//GEN-LAST:event_btnRemoveProductMouseClicked

    private void btnUpdateProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateProductMouseClicked
        UpdateProductView update = new UpdateProductView();
        update.setVisible(true);
    }//GEN-LAST:event_btnUpdateProductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);

            }

        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JPanel ProductsAreaPane;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnCadProduct;
    private javax.swing.JButton btnRemoveProduct;
    private javax.swing.JButton btnReturnMain;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JLabel cadProductLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
